### PR TITLE
Fix issues 60, 63, 65

### PR DESCRIPTION
**Pull request by stefanb2**

### CODE REVIEW

**Comment by shinh** [comment]
Could you look into the failure travis reported? Maybe you can do ENV.delete('MAKEFLAGS') or something at the beginning of runtest.rb?

**Comment by stefanb2** [comment]
BTW: is there a way to convince googlebot that I have signed the CLA?

**Comment by shinh** [comment]
Yeah, I was looking for the way. It seems you need to sign a corporate CLA at https://cla.developers.google.com/clas/new?domain=DOMAIN_GOOGLE&kind=KIND_CORPORATE with an @googlegroups.com address and join the group.

**Comment by shinh** [comment]
All look good, thanks!

**Pull request merged**
