### PR TITLE
Fix a typo

### PR DESCRIPTION
**Pull request by kou**

### CODE REVIEW

**Comment by shinh** [comment]
Thanks for the fix. Could you sign a CLA? You can find descriptions about it in https://github.com/google/kati/blob/master/CONTRIBUTING.md (sorry, I've just added this file)

**Comment by kou** [comment]
I've signed.
Should I also update AUTHORS or CONTRIBUTORS? (They don't exist yet.)
Because https://github.com/google/kati/blob/master/CONTRIBUTING.md#contributor-license-agreement says:

> Once your CLA is submitted (or if you already submitted one for another Google project), make a commit adding yourself to the AUTHORS and CONTRIBUTORS files. This commit can be part of your first pull request.

**Comment by shinh** [comment]
Oops, I'm still not familiar with Google's way to manage contributions... I've just added AUTHORS and CONTRIBUTORS, could you update your patch so they have your name?

**Comment by kou** [comment]
I've added me to CONTRIBUTORS.

**Comment by shinh** [comment]
Thanks!

**Comment by kou** [comment]
Thanks for your works for just "fix a typo"!

**Pull request merged**
