### PR TITLE
Randomize cpu affinity

### PR DESCRIPTION
**Pull request by danw**
Continue to lock kati to one or two CPUs, but pick one CPU at random,
and pick another CPU next to it. This dramatically speeds up cases where
more than one Kati instance is running at a time.

There's a multiproduct_build tool in Android that attempts to run Kati
on every build configuration present in the tree. My machine has 48
(including hyperthreading) cpu cores, with 64GB of ram. Before this
change, it would take ~12 minutes to build all 59 configurations, 12 at
a time. After this change it takes 3 minutes.

There doesn't seem to be any significant change in timings for
standalone builds. It looks like there was 1-2% difference with my
previous change that chose two completely random CPUs, but choosing two
that are likely hyperthreaded, or at least on the same chip helps.

### CODE REVIEW

**Comment by shinh** [comment]
Sorry for the messy code without any comment. I think the intention of this `n + 1` was that we give 2 virtual cores in a single real core. This setting worked very well for another project which had a few active threads which often sended messages each other. However, for kati's single threaded code, it seems just assigning random two cores works well.

**Comment by colincross** [comment]
Why does kati set affinity at all?  For a long-running single threaded process the kernel scheduling should be fine.

**Comment by danw** [comment]
I updated this to place the two cpu choices next to each other, which does seem to preserve the slight performance increase from this original change.

**Comment by shinh** [comment]
It seemed Linux kernel moves memory heavy threads from a core to another more often than we'd want. Setting affinity actually improves the performance by ~10% for me. I don't know much about Linux kernel's scheduler, but my guess was Linux kernel is not well tuned for such threads and really performance critical users, such as HPC, are setting affinity anyway. IIRC, Mac didn't move processes often and I thought we don't need the same hack for Mac.

**Pull request merged**
